/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.dynamic.data.mapping.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DDMFormInstanceReportEntry service. Represents a row in the &quot;DDMFormInstanceReportEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.dynamic.data.mapping.model.impl.DDMFormInstanceReportEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.dynamic.data.mapping.model.impl.DDMFormInstanceReportEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DDMFormInstanceReportEntry
 * @generated
 */
@ProviderType
public interface DDMFormInstanceReportEntryModel
	extends BaseModel<DDMFormInstanceReportEntry>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ddm form instance report entry model instance should use the {@link DDMFormInstanceReportEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this ddm form instance report entry.
	 *
	 * @return the primary key of this ddm form instance report entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ddm form instance report entry.
	 *
	 * @param primaryKey the primary key of this ddm form instance report entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this ddm form instance report entry.
	 *
	 * @return the mvcc version of this ddm form instance report entry
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this ddm form instance report entry.
	 *
	 * @param mvccVersion the mvcc version of this ddm form instance report entry
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the form instance report entry ID of this ddm form instance report entry.
	 *
	 * @return the form instance report entry ID of this ddm form instance report entry
	 */
	public long getFormInstanceReportEntryId();

	/**
	 * Sets the form instance report entry ID of this ddm form instance report entry.
	 *
	 * @param formInstanceReportEntryId the form instance report entry ID of this ddm form instance report entry
	 */
	public void setFormInstanceReportEntryId(long formInstanceReportEntryId);

	/**
	 * Returns the group ID of this ddm form instance report entry.
	 *
	 * @return the group ID of this ddm form instance report entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this ddm form instance report entry.
	 *
	 * @param groupId the group ID of this ddm form instance report entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this ddm form instance report entry.
	 *
	 * @return the company ID of this ddm form instance report entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ddm form instance report entry.
	 *
	 * @param companyId the company ID of this ddm form instance report entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this ddm form instance report entry.
	 *
	 * @return the create date of this ddm form instance report entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this ddm form instance report entry.
	 *
	 * @param createDate the create date of this ddm form instance report entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this ddm form instance report entry.
	 *
	 * @return the modified date of this ddm form instance report entry
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this ddm form instance report entry.
	 *
	 * @param modifiedDate the modified date of this ddm form instance report entry
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the form instance ID of this ddm form instance report entry.
	 *
	 * @return the form instance ID of this ddm form instance report entry
	 */
	public long getFormInstanceId();

	/**
	 * Sets the form instance ID of this ddm form instance report entry.
	 *
	 * @param formInstanceId the form instance ID of this ddm form instance report entry
	 */
	public void setFormInstanceId(long formInstanceId);

	/**
	 * Returns the summary of this ddm form instance report entry.
	 *
	 * @return the summary of this ddm form instance report entry
	 */
	@AutoEscape
	public String getSummary();

	/**
	 * Sets the summary of this ddm form instance report entry.
	 *
	 * @param summary the summary of this ddm form instance report entry
	 */
	public void setSummary(String summary);

}